language: cpp
compiler:
  - g++
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" ; fi 
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../src
  - make
script:
  - python ../test/run_test.py ./cpp-simplifier
addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-5
    - g++-5
    - cmake
    - cmake-data
    - libboost-program-options-dev
    - clang-3.8
    - libclang-common-3.8-dev
    - libclang-3.8-dev
    - libclang1-3.8
    - libllvm3.8
    - lldb-3.8
    - llvm-3.8
    - llvm-3.8-dev
    - llvm-3.8-runtime
    - lldb-3.8-dev
    - python-clang-3.8
sudo: false
