language: cpp
compiler:
  - g++
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" ; fi 
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ../src
  - make
script:
  - python ../test/run_test.py ./cpp-simplifier
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    packages:
    - gcc-5
    - g++-5
    - cmake3
    - cmake3-data
    - libboost-program-options-dev
    - clang-6.0
    - libclang-common-6.0-dev
    - libclang-6.0-dev
    - libclang1-6.0
    - libllvm6.0
    - lldb-6.0
    - llvm-6.0
    - llvm-6.0-dev
    - llvm-6.0-runtime
    - liblldb-6.0-dev
    - python-clang-6.0
sudo: false
